name: OpenCV Python Wheels

on:
  push:
    branches:
      - ga_test

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build wheels
        env:
          CI_BUILD: 1
        run: |
          python -m pip wheel --wheel-dir=dist . --verbose
#      - name: Install wheel
#        run: |
#          python -m pip install --user --no-warn-script-location (ls "../dist/opencovis_*.whl")
#      - name: Test wheel
#        run: |
#          python -m unittest test
#        with:
#          path: tests
